@Library('cb-days@master') _
def testPodYaml = libraryResource 'podtemplates/vuejs/vuejs-test-pod.yml'
pipeline {
  agent none
  options { 
    buildDiscarder(logRotator(numToKeepStr: '10'))
    //skipDefaultCheckout true
    preserveStashes(buildCount: 10)
  }
  environment {
    //Possible canary deploy phases:
    //1. Flag completely off
    //2. Flag turned on for internal testing
    //3. Flag turned on for internal testing + % subset of end users
    currentPhase = "fullyFalse"
    flagName = ""
    testsPass = false
    experimentYaml = ""
  }
  stages('Automatic Canary Deployment')
  {
    stage('Deployment Phase Check'){
       agent {
        kubernetes {
          label 'nodejs'
          yaml testPodYaml
        }
      }
      steps {
        checkout scm
        script{
          //Start of check if canary deploy shared library
          //env.experimentYaml = readYaml (text: "")
          currentInfo = ffCheckCanary()
          flagName = currentInfo[0]
          currentPhase = currentInfo[1]
          echo "currentPhase"
          if(currentPhase == "notCanary"){
            echo "Not a canary deployment!"
          }
        }
      }
    }
    stage('Automated Testing Kickoff'){
      when{
        expression { currentPhase != "notCanary"}
      }
      steps {
        script{
          testsPass = autoTesting()
          echo testsPass.toString()
        }
      }
    }
    stage('Canary scale up'){
      when{
        expression { testsPass == true && currentPhase != "notCanary"}
      }
      steps {
        echo "${currentPhase}"
        build job: 'FF-helper/FF-scale-up', parameters: [string(name:'currentPhase', value:"${currentPhase}"), string(name:'flagName', value:"${flagName}")], wait: true
      }
    }
    stage('Canary scale down'){
      when{
        expression { testsPass == false && currentPhase != "notCanary"}
      }
      steps {
        script{
          if(currentPhase!="fullyFalse" || currentPhase!="killSwitch"){
            echo "${currentPhase}"
            build job: 'FF-helper/FF-scale-down', parameters: [string(name:'currentPhase', value:"${currentPhase}"), string(name:'flagName', value:"${flagName}")], wait: true
          }
        }
      }
    }
  }
}
